# Base Image to use
FROM python:3.10.5-slim

# Change Working Directory to app directory
WORKDIR /app

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt \
    && rm -rf requirements.txt


# Choose port
EXPOSE 8081
ENTRYPOINT ["uvicorn", "app_fastapi:app", "--host", "0.0.0.0", "--port", "8081"]

