name: Trianer
description: Triathlon wrapper.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+3


environment:
  sdk: '>=2.12.0 <3.0.0'
  #flutter: ^2.10.5

dependencies:
  flutter:
    sdk: flutter
  url_launcher: any
  cupertino_icons: "any"
  webview_flutter: "any"
  syncfusion_flutter_sliders: "any"
  syncfusion_flutter_gauges: "any"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "any"
  #build_runner: ^2.1.2


#adaptive_icon_background: "#581845"
flutter_icons:
  image_path: "assets/logos/play_store_512.png"
  adaptive_icon_background: "#e6dce2"
  adaptive_icon_foreground: "assets/logos/res/mipmap-hdpi/ic_launcher_adaptive_fore.png"
  android: true
  ios: true
  remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/logos/play_store_512.png
